server:
  port: 8761
spring:
  application:
    name: registry-server
  security:
    user:
      name: dpc
      password: dpc123
  profiles:
    active: native
eureka:
  instance:
    metadata-map:
      user:
        name: ${spring.security.user.name}
        passsword: ${spring.security.user.password}
---
spring:
  profiles: native
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://dpc:dpc123@localhost:8761/eureka/
  server:
    peer-node-connection-idle-timeout-seconds: 5
    enable-self-preservation: false

---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://dpc:dpc123@peer2:8762/eureka/
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://dpc:dpc123@peer1:8761/eureka/